ports:
  - port: 8080
    onOpen: open-browser
tasks:
  - name: Build Contracts
    init: cd hardhat && npm i
    command: cd hardhat && yarn build
  - name: FrontEnd
    init: cd frontend && npm install
    command: cd frontend && npm run serve
  - name: Airnode
    init: yarn download-airnode
    command: yarn start-airnode
