ports:
  - port: 8080
    onOpen: open-preview
tasks:
  - name: Build Contracts
    init: cd hardhat && yarn build
  - name: Front End
    init: cd frontend && npm install
    command: npm run serve
  - name: Airnode
    init: yarn start-airnode
