ports:
  - port: 8080
    onOpen: open-preview
tasks:
  - name: Front End
    init: npm install
    command: npm run serve
  - name: Local Chain
    init: cd hardhat && npm i && npx hardhat node && gp sync-done node
  - name: hardhat
    init: gp sync-await node
    command: yarn deploy-contracts